app/models.py
#!/usr/bin/env python3
# -*- encoding: utf-8 -*-
"""
Flask + Python3 application template
Author: Frederico Freire Boaventura <frederico@boaventura.net>
URL: https://gitlab.com/ffb-portfolio/websites/flask-boilerplate
     https://github.com/fboaventura/flask-boilerplate
Licence: GPLv3
"""
from datetime import datetime
from hashlib import md5
from time import time
from flask import current_app
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
import jwt
from app import db, login


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password = db.Column(db.String(128))
    name = db.Column(db.String(500))
    about_me = db.Column(db.String(140))
    last_seen = db.Column(db.DateTime, default=datetime.utcnow())

    def __repr__(self):
        return '<User {}>'.format(self.username)

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    def avatar(self, size):
        digest = md5(self.email.lower().encode('utf-8')).hexdigest()
        return 'https://www.gravatar.com/avatar/{}?d=identicon&s={}'.format(
            digest, size)

    def get_reset_password_token(self, expires_in=600):
        return jwt.encode(
            {'reset_password': self.id, 'exp': time() + expires_in},
            current_app.config['SECRET_KEY'],
            algorithm='HS256').decode('utf-8')

    @staticmethod
    def verify_reset_password_token(token):
        try:
            user_id = jwt.decode(token, current_app.config['SECRET_KEY'],
                                 algorithms=['HS256'])['reset_password']
        except Exception:
            return

        return User.query.get(user_id)


@login.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/main/forms.py
#!/usr/bin/env python3
# coding: utf-8
# from flask import request
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import ValidationError, DataRequired, Length, Optional
from flask_babel import _, lazy_gettext as _l
from app.models import User


class EditProfileForm(FlaskForm):
    name = StringField(_l('Name'), validators=[Optional()])
    username = StringField(_l('Username'), validators=[DataRequired()])
    about_me = TextAreaField(_l('About me'), validators=[Length(min=0, max=140)])
    submit = SubmitField(_l('Submit'))

    def __init__(self, original_username, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        self.original_username = original_username

    def validate_username(self, username):
        if username.data != self.original_username:
            user = User.query.filter_by(username=self.username.data).first()
            if user is not None:
                raise ValidationError(_('Please use a different username'))

app/__init__.py
#!/usr/bin/env python3
# -*- encoding: utf-8 -*-
"""
Flask + Python3 application template
Author: Frederico Freire Boaventura <frederico@boaventura.net>
URL: https://gitlab.com/ffb-portfolio/websites/flask-boilerplate
     https://github.com/fboaventura/flask-boilerplate
Licence: GPLv3
"""
import os
import logging
from logging.handlers import SMTPHandler, RotatingFileHandler
from flask import Flask, request, current_app, g
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from flask_mail import Mail
from flask_moment import Moment
from flask_gravatar import Gravatar
from flask_bootstrap import Bootstrap
from flask_compress import Compress
from flask_caching import Cache
from flask_babel import Babel, lazy_gettext as _l
from config import Config

db = SQLAlchemy()  # flask-sqlalchemy
migrate = Migrate()  # flask-migrate
login = LoginManager()  # flask-login
login.login_view = 'auth.login'
login.login_message = _l('Please login to access this page.')
mail = Mail()
moment = Moment()
gravatar = Gravatar(
    app=None,
    size=100,
    rating='g',
    default='robohash',
    force_default=False,
    force_lower=False,
    use_ssl=True,
    base_url=None
)
bootstrap = Bootstrap()  # flask-bootstrap
cache = Cache()  # flask-caching
compress = Compress()  # flask-compress
babel = Babel()  # flask-babel


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    migrate.init_app(app, db)
    login.init_app(app)
    mail.init_app(app)
    moment.init_app(app)
    gravatar.init_app(app)
    bootstrap.init_app(app)
    compress.init_app(app)
    cache.init_app(app)
    babel.init_app(app)

    from app.auth import bp as auth_blueprint
    app.register_blueprint(auth_blueprint)

    from .main import bp as main_blueprint
    app.register_blueprint(main_blueprint)

    if not app.debug and not app.testing:
        if app.config['MAIL_SERVER']:
            auth = None
            if app.config['MAIL_USERNAME'] or app.config['MAIL_PASSWORD']:
                auth = (app.config['MAIL_USERNAME'],
                        app.config['MAIL_PASSWORD'])
            secure = None
            if app.config['MAIL_USE_TLS']:
                secure = ()
            mail_handler = SMTPHandler(
                mailhost=(app.config['MAIL_SERVER'], app.config['MAIL_PORT']),
                fromaddr='no-reply@' + app.config['MAIL_SERVER'],
                toaddrs=app.config['ADMINS'], subject='{} Failure'.format(current_app.config.APP_NAME),
                credentials=auth, secure=secure)
            mail_handler.setLevel(logging.ERROR)
            app.logger.addHandler(mail_handler)

        if not os.path.exists('logs'):
            os.mkdir('logs')
        file_handler = RotatingFileHandler('logs/app.log',
                                           maxBytes=10240, backupCount=10)
        file_handler.setFormatter(logging.Formatter(
            '%(asctime)s %(levelname)s: %(message)s '
            '[in %(pathname)s:%(lineno)d]'))
        file_handler.setLevel(logging.INFO)
        app.logger.addHandler(file_handler)

        app.logger.setLevel(logging.INFO)
        app.logger.info('{} startup'.format(current_app.config.APP_NAME))

    return app


@babel.localeselector
def get_locale():
    # Check if a language code is already defined
    if not g.get('lang_code', None):
        # Otherwise set one from the best match from the list of configured languages
        g.lang_code = request.accept_languages.best_match(current_app.config['LANGUAGES'])
    return g.lang_code

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
#!/usr/bin/env python3
# coding: utf-8

from datetime import datetime
from flask import render_template, flash, redirect, url_for, request, g
from flask_login import current_user, login_required
from flask_babel import _, get_locale
from app import db
from app.main.forms import EditProfileForm
from app.models import User
from app.main import bp


@bp.before_app_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()
    g.locale = str(get_locale())


@bp.route('/', methods=['GET', 'POST'])
@bp.route('/index', methods=['GET', 'POST'])
@login_required
def index():
    user = User.query.filter_by(username=current_user.username).first_or_404()
    return render_template('index.html', title=_('Home'), user=user)


@bp.route('/user/<username>')
@login_required
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    return render_template('user.html', user=user)


@bp.route('/edit_profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm(current_user.username)
    if form.validate_on_submit():
        print('form:', form)
        current_user.username = form.username.data
        current_user.about_me = form.about_me.data
        current_user.name = form.name.data
        # current_user.email = form.email.data
        db.session.commit()
        flash(_('Your changes have been saved'))
        return redirect(url_for('main.edit_profile'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.about_me.data = current_user.about_me
        form.name.data = current_user.name
        # form.email.data = current_user.email

    return render_template('edit_profile.html', page_title=_('Edit Profile'), form=form)

app/templates/base.html
{% extends "bootstrap/base.html" %}

{# Block for Page Title #}
{% block title %}
    {% if title %}{{ title }}{% else %}.: Flask-Boilerplate :.{% endif %}
{% endblock title %}

{# Block for Head section #}
{% block head %}
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/png">
    {{ super() }}
{% endblock head %}

{# Block for meta tags #}
{% block metas %}
    {{ super() }}
{% endblock metas %}

{# Block for CSS styles #}
{% block styles %}
    {{ super() }}
    <link rel="stylesheet" type="text/css"
          href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
{% endblock styles %}

{# Block for JS scripts #}
{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
    <script src="{{ url_for('static', filename='js/app.js') }}"></script>
{% endblock scripts %}

{# Block for Navigation Bar #}
{% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-expand-md navbar-light bg-light">
        <div class="container">
            {# Uncomment the line below to use an image as the NavBar Icon #}
            {#  <a class="navbar-brand" href="/"><img src="{{ url_for('static', filename='images/logo.png') }}"></a>#}
            <a class="navbar-brand" href="/">MySiteName</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">{% trans %}Home{% endtrans %} <span class="sr-only">{% trans %}(current){% endtrans %}</span></a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Posts
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#"><i class="fa fa-list"></i> List</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#"><i class="fa fa-plus"></i> New</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#">Disabled</a>
                    </li>
                </ul>
                {#      SEARCH FORM - BEGIN     #}
                {#    <form class="form-inline my-2 my-lg-0">#}
                {#      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">#}
                {#      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>#}
                {#    </form>#}
                {#      SEARCH FORM - END #}
                {#      SIMPLE PROFILE DROPDOWN - BEGIN #}
                {#    <ul class=""navbar-nav>#}
                {#    <!-- PROFILE DROPDOWN - scrolling off the page to the right -->#}
                {#        <li class="nav-item dropdown">#}
                {#            <a href="#" class="nav-link dropdown-toggle" id="navDropDownLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">#}
                {#        Profile#}
                {#            </a>#}
                {#            <div class="dropdown-menu" aria-labelledby="navDropDownLink">#}
                {#                <a class="dropdown-item" href="#">Preferences</a>#}
                {#                <div class="dropdown-divider"></div>#}
                {#                <a class="dropdown-item" href="#">Logout</a>#}
                {#            </div>#}
                {#        </li>#}
                {#    </ul>#}
                {#      SIMPLE PROFILE DROPDOWN - END #}
                <ul class="nav navbar-nav navbar-right">

                    {% if current_user.is_anonymous %}
                        <li><a href="{{ url_for('auth.login') }}">{{ _('Login') }}</a></li>
                    {% else %}
                        <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        {{ current_user.username }}
                        {#                        Account#}
                        <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>
                                <div class="navbar-content">
                                    <div class="row">
                                        <div class="col-md-5">
                                            <img src="{{ current_user.email|gravatar(size=120) }}"
                                                 alt="Alternate Text" class="img-responsive"/>
                                            {#                                            <p class="text-center small">#}
                                            {#                                                <a href="#">Change Photo</a></p>#}
                                        </div>
                                        <div class="col-md-7">
                                            <span>{{ current_user.name }}</span>
                                            <p class="text-muted small">{{ current_user.email }}</p>
                                            <div class="divider">
                                            </div>
                                            <a href="{{ url_for('main.user', username=current_user.username) }}"
                                               class="btn btn-primary btn-sm active">View Profile</a>
                                        </div>
                                    </div>
                                </div>
                                <div class="navbar-footer">
                                    <div class="navbar-footer-content">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <a href="#" class="btn btn-default btn-sm">_('Change Password')</a>
                                            </div>
                                            <div class="col-md-6">
                                                <a href="{{ url_for('auth.logout') }}"
                                                   class="btn btn-default btn-sm pull-right">_('Logout')</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    {% endif %}
                    </li>
                </ul>

            </div>
        </div>
    </nav>
{% endblock navbar %}

{# Block for main content container #}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col col-12">
                <div class="title text-center h1 mb-4">{% block page_title %}Home{% endblock %}</div>
            </div>
        </div>
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }}" role="alert">
                        {{ message|safe }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}

        {# application content goes inside app_content block #}
        {% block app_content %}{% endblock app_content %}
    </div>
    <footer class="footer fixed-bottom bg-light border-top mt-4 ">
        <div class="container pt-2 footer-copyright text-center small">
            <span class="text-muted"><a href="//frederico.cf" class="text-primary">Frederico Freire Boaventura</a> <i
                    class="fa fa-copyright"></i> 2019-2019</span>
        </div>
    </footer>
{% endblock content %}

app/templates/bootstrap/base.html
{% block doc -%}
<!doctype html>
<html{% block html_attribs %}{% endblock html_attribs %}>
{%- block html %}
    <head>
        {%- block metas %}
            <!-- Required meta tags -->
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        {%- endblock metas %}

        {%- block head %}
            <title>{% block title %}{{ title|default }}{% endblock title %}</title>

            {%- block styles %}
                <!-- Bootstrap -->
                {{ bootstrap.load_css() }}
            {%- endblock styles %}
        {%- endblock head %}
    </head>
    <body{% block body_attribs %}{% endblock body_attribs %}>
    {% block body -%}
        {% block navbar %}
        {%- endblock navbar %}
        {% block content -%}
        {%- endblock content %}

        {% block scripts %}
            {{ bootstrap.load_js() }}
        {%- endblock scripts %}
    {%- endblock body %}
    </body>
{%- endblock html %}
</html>
{% endblock doc -%}

app/templates/bootstrap/wtf.html
{% macro form_errors(form, hiddens=True) %}
  {%- if form.errors %}
    {%- for fieldname, errors in form.errors.items() %}
      {%- if bootstrap_is_hidden_field(form[fieldname]) and hiddens or
             not bootstrap_is_hidden_field(form[fieldname]) and hiddens != 'only' %}
        {%- for error in errors %}
          <div class="invalid-feedback">{{error}}</div>
        {%- endfor %}
      {%- endif %}
    {%- endfor %}
  {%- endif %}
{%- endmacro %}

{% macro _hz_form_wrap(horizontal_columns, form_type, add_group=False, required=False) %}
{% if form_type == "horizontal" %}
  {% if add_group %}<div class="form-group row{% if required %} required{% endif %}">{% endif %}
  <div class="offset-{{horizontal_columns[0]}}-{{horizontal_columns[1]}}
              col-{{horizontal_columns[0]}}-{{horizontal_columns[2]}}
             ">
{% endif %}
{{caller()}}

{% if form_type == "horizontal" %}
  {% if add_group %}</div>{% endif %}
  </div>
{% endif %}
{% endmacro %}

{% macro form_field(field,
                    form_type="basic",
                    horizontal_columns=('lg', 2, 10),
                    button_map={}) %}

{# this is a workaround hack for the more straightforward-code of just passing required=required parameter. older versions of wtforms do not have
the necessary fix for required=False attributes, but will also not set the required flag in the first place. we skirt the issue using the code below #}
{% if field.flags.required and not required in kwargs %}
{% set kwargs = dict(required=True, **kwargs) %}
{% endif %}

{% if field.widget.input_type == 'checkbox' %}
  {% call _hz_form_wrap(horizontal_columns, form_type, True, required=required) %}
    <div class="form-check{% if form_type == "inline" %} form-check-inline{% endif %}">
      <label class="form-check-label">
        {{field(class_="form-check-input")|safe}} {{field.label.text|safe}}
      </label>
    </div>
  {% endcall %}
{%- elif field.type == 'RadioField' -%}
  {# note: A cleaner solution would be rendering depending on the widget,
     this is just a hack for now, until I can think of something better #}
  {% call _hz_form_wrap(horizontal_columns, form_type, True, required=required) %}
    {% for item in field -%}
      <div class="form-check{% if form_type == "inline" %} form-check-inline{% endif %}">
        <label class="form-check-label">
          {{item(class_="form-check-input")|safe}} {{item.label.text|safe}}
        </label>
      </div>
    {% endfor %}
  {% endcall %}
{%- elif field.type == 'SubmitField' -%}
  {# deal with jinja scoping issues? #}
  {% set field_kwargs = kwargs %}

  {# note: same issue as above - should check widget, not field type #}
  {% call _hz_form_wrap(horizontal_columns, form_type, True, required=required) %}
    {{field(class='btn btn-%s' % button_map.get(field.name, 'primary'),
            **field_kwargs)}}
  {% endcall %}
{%- elif field.type == 'FormField' -%}
{# note: FormFields are tricky to get right and complex setups requiring
   these are probably beyond the scope of what this macro tries to do.
   the code below ensures that things don't break horribly if we run into
   one, but does not try too hard to get things pretty. #}
  <fieldset>
    <legend>{{field.label}}</legend>
    {%- for subfield in field %}
      {% if not bootstrap_is_hidden_field(subfield) -%}
        {{ form_field(subfield,
                      form_type=form_type,
                      horizontal_columns=horizontal_columns,
                      button_map=button_map) }}
      {%- endif %}
    {%- endfor %}
  </fieldset>
{% else -%}
  <div class="form-group {% if field.errors %} has-danger{% endif -%}
                         {%- if form_type == "horizontal" %} row{% endif -%}
                         {%- if field.flags.required %} required{% endif -%}
  ">
      {%- if form_type == "inline" %}
        {{field.label(class="sr-only")|safe}}
        {% if field.type == 'FileField' %}
          {{field(class="form-control-file", **kwargs)|safe}}
        {% else %}
          {{field(class="form-control mb-2 mr-sm-2 mb-sm-0", **kwargs)|safe}}
        {% endif %}
      {% elif form_type == "horizontal" %}
        {{field.label(class="form-control-label " + (
          " col-%s-%s" % horizontal_columns[0:2]
        ))|safe}}
        <div class=" col-{{horizontal_columns[0]}}-{{horizontal_columns[2]}}">
          {% if field.type == 'FileField' %}
            {{field(class="form-control-file", **kwargs)|safe}}
          {% else %}
            {{field(class="form-control", **kwargs)|safe}}
          {% endif %}
        </div>
        {%- if field.errors %}
          {%- for error in field.errors %}
            {% call _hz_form_wrap(horizontal_columns, form_type, required=required) %}
              <div class="invalid-feedback">{{error}}</div>
            {% endcall %}
          {%- endfor %}
        {%- elif field.description -%}
          {% call _hz_form_wrap(horizontal_columns, form_type, required=required) %}
            <small class="form-text text-muted">{{field.description|safe}}</small>
          {% endcall %}
        {%- endif %}
      {%- else -%}
        {{field.label(class="form-control-label")|safe}}
        {% if field.type == 'FileField' %}
          {{field(class="form-control-file", **kwargs)|safe}}
        {% else %}
          {{field(class="form-control", **kwargs)|safe}}
        {% endif %}

        {%- if field.errors %}
          {%- for error in field.errors %}
            <div class="invalid-feedback">{{error}}</div>
          {%- endfor %}
        {%- elif field.description -%}
          <small class="form-text text-muted">{{field.description|safe}}</small>
        {%- endif %}
      {%- endif %}
  </div>
{% endif %}
{% endmacro %}

{# valid form types are "basic", "inline" and "horizontal" #}
{% macro quick_form(form,
                    action="",
                    method="post",
                    extra_classes=None,
                    role="form",
                    form_type="basic",
                    horizontal_columns=('lg', 2, 10),
                    enctype=None,
                    button_map={},
                    id="",
                    novalidate=False,
                    render_kw={}) %}
{#-
action="" is what we want, from http://www.ietf.org/rfc/rfc2396.txt:

4.2. Same-document References

   A URI reference that does not contain a URI is a reference to the
   current document.  In other words, an empty URI reference within a
   document is interpreted as a reference to the start of that document,
   and a reference containing only a fragment identifier is a reference
   to the identified fragment of that document.  Traversal of such a
   reference should not result in an additional retrieval action.
   However, if the URI reference occurs in a context that is always
   intended to result in a new request, as in the case of HTML's FORM
   element, then an empty URI reference represents the base URI of the
   current document and should be replaced by that URI when transformed
   into a request.

 -#}
{#- if any file fields are inside the form and enctype is automatic, adjust
    if file fields are found. could really use the equalto test of jinja2
    here, but latter is not available until 2.8

    warning: the code below is guaranteed to make you cry =(
#}
{%- set _enctype = [] %}
{%- if enctype is none -%}
  {%- for field in form %}
    {%- if field.type == 'FileField' %}
      {#- for loops come with a fairly watertight scope, so this list-hack is
          used to be able to set values outside of it #}
      {%- set _ = _enctype.append('multipart/form-data') -%}
    {%- endif %}
  {%- endfor %}
{%- else %}
  {% set _ = _enctype.append(enctype) %}
{%- endif %}
<form
  {%- if action != None %} action="{{action}}"{% endif -%}
  {%- if id %} id="{{id}}"{% endif -%}
  {%- if method %} method="{{method}}"{% endif %}
  class="form
    {%- if extra_classes %} {{extra_classes}}{% endif -%}
    {%- if form_type == "inline" %} form-inline{% endif -%}
  "
  {%- if _enctype[0] %} enctype="{{_enctype[0]}}"{% endif -%}
  {%- if role %} role="{{role}}"{% endif -%}
  {%- if novalidate %} novalidate{% endif -%}
  {%- if render_kw %} {{render_kw|xmlattr}}{% endif -%}
  >
  {{ form.hidden_tag() }}
  {{ form_errors(form, hiddens='only') }}

  {%- for field in form %}
    {% if not bootstrap_is_hidden_field(field) -%}
      {{ form_field(field,
                    form_type=form_type,
                    horizontal_columns=horizontal_columns,
                    button_map=button_map) }}
    {%- endif %}
  {%- endfor %}

</form>
{%- endmacro %}

app/templates/edit_profile.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}


{% block page_title %}
    {{ _('Edit Profile') }}
{% endblock page_title %}

{% block app_content %}
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block title %}Index{% endblock title %}

{% block page_title %}Index{% endblock page_title %}
{% block app_content %}
	<div class="row">
		<div class="span4">
			<img src="http://placehold.it/360x200" class="img-polaroid" alt="">
		</div>
		<div class="span4">
			<img src="http://placehold.it/360x200" class="img-polaroid" alt="">
		</div>
		<div class="span4">
			<img src="http://placehold.it/360x200" class="img-polaroid" alt="">
		</div>
	</div>
{% endblock app_content %}

app/templates/list.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Lista!{% endblock %}

{% block app_content %}

	<h1>Listagem</h1>
	
	<div class="row">
		<div class="span12">

			Listagem...

			<table class="table">
				<tr>
					<th>Coluna 1</th>
					<th>Coluna 2</th>
					<th>Coluna 3</th>
					<th>Coluna 4</th>
					<th>Coluna 5</th>
					<th>Coluna 6</th>
				</tr>
				<tr>
					<td>valor 1</td>
					<td>valor 2</td>
					<td>valor 3</td>
					<td>valor 4</td>
					<td>valor 5</td>
					<td>valor 6</td>
				</tr>
				<tr>
					<td>valor 1</td>
					<td>valor 2</td>
					<td>valor 3</td>
					<td>valor 4</td>
					<td>valor 5</td>
					<td>valor 6</td>
				</tr>
				<tr>
					<td>valor 1</td>
					<td>valor 2</td>
					<td>valor 3</td>
					<td>valor 4</td>
					<td>valor 5</td>
					<td>valor 6</td>
				</tr>
				<tr>
					<td>valor 1</td>
					<td>valor 2</td>
					<td>valor 3</td>
					<td>valor 4</td>
					<td>valor 5</td>
					<td>valor 6</td>
				</tr>
			</table>

		</div>
	</div>

{% endblock app_content %}

app/templates/new.html
{% extends "base.html" %}
{% import "bootstrap_wtf.html" as wtf %}

{%block title%}Novo!{%endblock%}

{%block main_content%}

	<h1>Novo</h1>
	<div class="row">
		<div class="span12">

			<form action="/save/" method="post" name="exampleform">
				{{ wtf.form_errors(form,"only") }}

				{{ form.hidden_tag() }}
				{{ wtf.horizontal_field(form.title) }}<br>
				{{ wtf.horizontal_field(form.content) }}
				{{ wtf.horizontal_field(form.date) }}
				{# wtf.horizontal_field(form.recaptcha) #}

				<div class="form-actions">
					<button name-"action_save" type="submit" class="btn btn-primary">Salvar</button>
				</div>
			</form>

		</div>
	</div>

{%endblock%}

app/templates/user.html
{% extends "base.html" %}

{% block page_title %}{% endblock page_title %}

{% block app_content %}
    <table class="table table-hover">
        <tr>
            <td><img src="{{ current_user.email|gravatar(size=256) }}" alt=""></td>
            <td>
                <h1>{{ _('User') }}: {{ user.username }}</h1>
                {% if user.name %}<p>{{ user.name }}</p>{% endif %}
                {% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}
                {% if user.last_seen %}
                    <p>{{ _('Last seen on') }}: {{ moment(user.last_seen).format('LLL') }}</p>
                {% endif %}
                {% if user == current_user %}
                <p>
                    <a href="{{ url_for('main.edit_profile') }}">{{ _('Edit your profile') }}</a>
                </p>
                {% else %}
                    <p>
                        <a href="{{ url_for('main.send_message', recipient=user.username) }}">{{ _('Send private message') }}</a>
                    </p>
                {% endif %}
            </td>
        </tr>
    </table>
{% endblock app_content %}